project 'GPUImage-视频采集.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPUImage-视频采集' do

pod "GPUImage"
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GPUImage-视频采集

  target 'GPUImage-视频采集Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPUImage-视频采集UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

